### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by chippers** [chippers/flatc.rs#1]
Windows support is not currently supported. Windows support is desired and will be a requirement for version `1.0`, but I don't have any environments to be able to test/develop it myself.

# MSVC
Windows on MSVC typically turns warning into errors and fails the build. Flatbuffer's own CI seems to support both Visual Studio 2017 and 2019 so I'm not sure why it's failing.

# GNU
The final executable fails to pass the `flatc_exists` tests, but I don't have an environment to debug it.

**Comment by JWorthe** [comment]
The `flatc_exists` failing is because the executable on windows is `flatc.exe` (not `flatc`)

**Comment by chippers** [comment]
I haven't tested it by hand, but the CI is happy with both MSVC and GNU toolchains. Thank you @JWorthe for the Windows support!

https://github.com/chippers/flatc.rs/actions/runs/1016802684

I have a small windows VM I set up recently so maybe I'll set up the toolchains required and try it by hand soon too.
